public class DesignCafeConstants {
    public static String CALL_NOTCONTACTED                  = 'No Response';
    public static String LEADSTAGE_NORESPONSE               = 'No Response';
    public static String LEADSTAGE_DEAD                     = 'Dead';
    public static String STATUS_JUNK                        = 'JUNK';
    public static String LEADSTAGE_MEETINGSCHEDULED         = 'Meeting Scheduled';
    public static String LEADSTAGE_MEETINGDONE              = 'Meeting Done';
    public static String LEADSTAGE_PREQUALIFIED             = 'Pre-qualified';
    public static String LEADSTAGE_QUALIFIED                = 'Qualified';
    public static String CALLSTAGE_ATTEMPTSDONE             = 'All attempts done';
    // Task 
    public static String TASK_STATUS_COMPLETED              = 'Completed';
    public static String TASK_STATUS_OPEN                   = 'Open';
    public static String TASK_SUBJECT                       = 'Followup Reminder.';
    
    // USER Roles
    public static String ROLE_INTERNALSALESAGENT            ='Internal Sales Agent';
    public static String ROLE_CHM                           ='CHM'; 
    public static String ROLE_Survey                        ='Survey Team';
    public static String ROLE_PM                            ='Project Manager';
    public static String ROLE_3DShellDesigner               ='3D Shell Designer';
    
    // Record Type Names
    public static String RECTYPE_SALESPARTNER               = 'Sales Partner';
    public static String RECTYPE_EMPLOYEE                   = 'Employee';
    
    
}